services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cvtiga-postgres
    environment:
      POSTGRES_DB: afms_database
      POSTGRES_USER: afms_user
      POSTGRES_PASSWORD: afms_secure_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./laravel-api/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - cvtiga-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U afms_user -d afms_database"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Laravel API
  laravel-api:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    container_name: cvtiga-laravel-api
    environment:
      - APP_NAME=AFMS
      - APP_ENV=production
      - APP_KEY=base64:afms-laravel-app-key-production-2024-secure-base64-encoded-key
      - APP_DEBUG=false
      - APP_URL=https://api.cvtigaputraperkasa.id
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=afms_database
      - DB_USERNAME=afms_user
      - DB_PASSWORD=afms_secure_password_2024
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - BROADCAST_DRIVER=redis
    volumes:
      - ./laravel-api:/var/www/html
      - laravel_storage:/var/www/html/storage
      - laravel_bootstrap_cache:/var/www/html/bootstrap/cache
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cvtiga-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cvtiga-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - cvtiga-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  laravel_storage:
    driver: local
  laravel_bootstrap_cache:
    driver: local

networks:
  cvtiga-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16