version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cvtiga-postgres
    environment:
      POSTGRES_DB: afms_database
      POSTGRES_USER: afms_user
      POSTGRES_PASSWORD: afms_secure_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./laravel-api/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - cvtiga-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U afms_user -d afms_database"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Laravel API
  laravel-api:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    container_name: cvtiga-laravel-api
    environment:
      - APP_NAME=AFMS
      - APP_ENV=production
      - APP_KEY=base64:afms-laravel-app-key-production-2024-secure-base64-encoded-key
      - APP_DEBUG=false
      - APP_URL=https://api.cvtigaputraperkasa.id
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=afms_database
      - DB_USERNAME=afms_user
      - DB_PASSWORD=afms_secure_password_2024
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - BROADCAST_DRIVER=redis
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-app-password
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=noreply@cvtigaputraperkasa.id
      - MAIL_FROM_NAME=AFMS
      - FINGERPRINT_DEVICE_IP=192.168.1.100
      - FINGERPRINT_DEVICE_PORT=4370
      - FINGERPRINT_DEVICE_PASSWORD=123456
      - FINGERPRINT_DEVICE_TIMEOUT=30
      - NEXTJS_API_URL=https://cvtigaputraperkasa.id/api
      - NEXTJS_API_TOKEN=afms-nextjs-api-token-production
      - API_RATE_LIMIT=100
      - JWT_SECRET=afms-jwt-secret-key-production-2024-very-secure
      - JWT_TTL=60
    volumes:
      - ./laravel-api:/var/www/html
      - laravel_storage:/var/www/html/storage
      - laravel_bootstrap_cache:/var/www/html/bootstrap/cache
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cvtiga-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: cvtiga-nextjs
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.cvtigaputraperkasa.id
      - NEXT_PUBLIC_APP_NAME=AFMS
      - NEXT_PUBLIC_APP_VERSION=1.0.0
      - API_SECRET_TOKEN=afms-nextjs-api-token-production
    # volumes:
      # - .:/app  # Removed: This overrides the built standalone app
      # - nextjs_node_modules:/app/node_modules
      # - nextjs_next:/app/.next
    depends_on:
      - laravel-api
    networks:
      - cvtiga-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cvtiga-redis
    command: redis-server --appendonly yes --requirepass afms_redis_password_2024
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - cvtiga-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: cvtiga-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certs:/etc/nginx/ssl
      - ./ssl/www:/var/www/certbot
      - nginx_logs:/var/log/nginx
    depends_on:
      - laravel-api
      - nextjs
    networks:
      - cvtiga-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: cvtiga-certbot
    volumes:
      - ./ssl/certs:/etc/letsencrypt
      - ./ssl/private:/etc/letsencrypt/live
      - ./ssl/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@cvtigaputraperkasa.id --agree-tos --no-eff-email -d cvtigaputraperkasa.id -d api.cvtigaputraperkasa.id
    networks:
      - cvtiga-network
    profiles:
      - ssl-setup

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  laravel_storage:
    driver: local
  laravel_bootstrap_cache:
    driver: local
  nextjs_node_modules:
    driver: local
  nextjs_next:
    driver: local
  nginx_logs:
    driver: local

networks:
  cvtiga-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16