# Docker Compose Override for Development
# This file is automatically loaded by docker-compose

version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=AFMS - Attendance & Fingerprint Management System
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=/api
    volumes:
      # Mount styles for hot reload in development
      - ./styles:/app/styles:ro
      - ./public:/app/public:ro
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    environment:
      - POSTGRES_DB=afms_database
      - POSTGRES_USER=afms_user
      - POSTGRES_PASSWORD=afms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  redis:
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: afms_network
    driver: bridge